### ISSUE TITLE
Hey Geoffroy Givry 

### ISSUE THREAD

**Issue by tws0002** [geoffroygivry/CyclopsVFX-Unity#1]
Hey Geoffroy Givry, 

Still working in ILM Singapore?
Finally, see you continue working on CyclopsVFX pipeline. 
when will you do some documentation or video to demo this pipeline?

Cheers 
Desmond

**Comment by geoffroygivry** [comment]
Hi Desmond,
Great to hear from you and I hope you are doing well.. 
Yes Still at ILM Singapore, but I'm moving to ILM London in a August. Exciting times!
I sent you a private message.
Speak to you soon.
Geoff
